CREATE TABLE TEAM (
    TeamID INT AUTO_INCREMENT PRIMARY KEY,
    TeamName VARCHAR(30)
);

CREATE TABLE GAME (
    gameId INT AUTO_INCREMENT PRIMARY KEY,
    home INT REFERENCES TEAM(TeamID),
    away INT REFERENCES TEAM(TeamID),
    date Date
);

Create table INNING (
	inningId INT AUTO_INCREMENT PRIMARY KEY,
	inningPartId INT REFERENCES INNING_PART(inningPartId),
	gameId INT REFERENCES GAME(gameId),
	inningNumber INT
);

CREATE TABLE INNING_PART (
    inningPartId INT AUTO_INCREMENT PRIMARY KEY,
    inningPartName VARCHAR(10)
);

CREATE TABLE PLAY (
    playId INT PRIMARY KEY,
    gameId INT REFERENCES GAME(GameID),
    inningId INT REFERENCES INNING(InningID),
    playPerGame INT
);

CREATE TABLE PLAY_EVENT (
    playEventID INT AUTO_INCREMENT PRIMARY KEY,
    eventID INT,
    playID INT,
    FOREIGN KEY (eventID) REFERENCES EVENT(eventID),
    FOREIGN KEY (playID) REFERENCES PLAY(playID)
);

CREATE TABLE EVENT (
    eventID INT AUTO_INCREMENT PRIMARY KEY,
    eventName VARCHAR(50),
    eventCode INT,
);

CREATE TABLE TEAM_PLAYER(
	TeamPlayerID INT AUTO_INCREMENT PRIMARY KEY,
	PlayerID INT REFERENCES PLAYER(PlayerID),
	TeamID INT REFERENCES TEAM(TeamID)
);

CREATE TABLE PLAYER(
	PlayerID INT AUTO_INCREMENT PRIMARY KEY,
	PlayerNum INT 
);

CREATE TABLE PLAYER_PLAY(
	PlayerPlayID INT AUTO_INCREMENT PRIMARY KEY,
	PlayID INT REFERENCES PLAY(PlayID),
	PositionID INT REFERENCES POSITION(PositionID),
	PlayerID INT REFERENCES PLAYER(PlayerID)
);

CREATE TABLE POSITION(
	PositionID INT AUTO_INCREMENT PRIMARY KEY,
	PosCode INT,
	PosName VARCHAR(30)
);

CREATE TABLE PLAYER_MOMENT(
	PlayerMomentID INT AUTO_INCREMENT PRIMARY KEY,
	PlayerPlayID INT REFERENCES  PLAYER_PLAY(PlayerPlayID),
	TimeStamp INT,
	FieldX NUMERIC(8,4),
	FieldY NUMERIC(8,4)
);

CREATE TABLE BALL_POS(
	BallPosID INT AUTO_INCREMENT PRIMARY KEY,
	PlayID INT REFERENCES PLAY(PlayID),
	TimeStamp INT,
	BallPositionX NUMERIC(8,4),
	BallPositionY NUMERIC(8,4),
	BallPositionZ NUMERIC(8,4)
)


